# -*- coding: utf-8 -*-
print("Hello, World!")
print('The quick brown fox', 'jumps over', 'the lazy dog')
print('100 + 200 =', 100 + 200)
print('请输入姓名：')
name = input()
print('请输入年龄：')
age = input()
print('请输入性别：')
sex = input()
print('姓名：{}，年龄：{}，性别：{}。', name, age, sex)
